version: '3.8'

services:
  test-runner:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
